app_id: "...."
app_secret: "...."
redirect: "http://localhost:8000/callback"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
  - files.readwrite
authority: "https://login.microsoftonline.com/common"
